<?php
/**
 * Created by PhpStorm.
 * User: Mehedee
 * Date: 1/5/2019
 * Time: 12:22 PM
 */

class OpsSelectOption  
{
	public static function CountryName()
	{
		return [
			"",
			"Bahamas",
			"Bermuda",
			"Canada",
			"Jamaica",
			"Mexico",
			"USA",
			"==========================",
			"Andorra",
			"Argentina",
			"Australia",
			"Austria",
			"Azerbaidjan",
			"Bahrain",
			"Bangladesh",
			"Belgium",
			"Bolivia",
			"Brazil",
			"Bulgaria",
			"Chile",
			"China",
			"Colombia",
			"Croatia",
			"Czech Republic",
			"Denmark",
			"Dominican Republic",
			"Ecuador",
			"El Salvador",
			"Ethiopia",
			"Fiji",
			"Finland",
			"France",
			"Germany",
			"Ghana",
			"Guam",
			"Honduras",
			"Hong Kong",
			"Hungary",
			"India",
			"Indonesia",
			"Ireland",
			"Israel",
			"Italy",
			"Jamaica",
			"Japan",
			"Jordan",
			"Kenya",
			"Korea",
			"Latvia",
			"Luxembourg",
			"Macau",
			"Malaysia",
			"Mauritius",
			"Monaco",
			"Myanmar",
			"Nepal",
			"Netherlands",
			"New Caledonia",
			"New Guinea",
			"New Zealand",
			"Nigeria",
			"Norway",
			"Pakistan",
			"Panama",
			"Paraguay",
			"Peru",
			"Philippines",
			"Portugal",
			"Romania",
			"Singapore",
			"South Africa",
			"Spain",
			"Sri Lanka",
			"Sweden",
			"Switzerland",
			"Taipei",
			"Tallinn",
			"Thailand",
			"Turkey",
			"Uganda",
			"United Kingdom",
			"Uruguay",
			"Vanuatu",
			"Venezuela",
			"Zimbabwe",
		];
	}

	public static function ClubName()
	{
		return[
			"",
			"Acapulco",
			"Albany",
			"Anchorage",
			"Arkansas",
			"Atlanta",
			"Atlantic City",
			"Austin",
			"Bahamas",
			"Bahias de Huatulco",
			"Baltimore",
			"Bermuda",
			"Boise",
			"Boston",
			"Calgary",
			"Canadian Rockies",
			"Cancun",
			"Central Pensylvania",
			"Charlotte",
			"Chicago",
			"Ciudad de Mexico",
			"Colorado",
			"Columbus",
			"Cozumel",
			"Edmonton",
			"Fort Lauderdale & Palm Beaches",
			"Fort Worth",
			"Guadalajara",
			"Guanajuato",
			"Halifax",
			"Hamilton",
			"Hawaii",
			"Isla Mujeres-Puerto Murelos",
			"Ixtapa",
			"Jacksonville",
			"Kansas City",
			"Kingston",
			"Las Vegas",
			"London",
			"Long Island",
			"Los Angeles",
			"Los Cabos",
			"Louisville",
			"Manzanillo-Colima-Costalegre",
			"Mazatlan",
			"Memphis",
			"Merida",
			"Miami",
			"Monterrey",
			"Montréal",
			"Myrtle Beach",
			"Nashville",
			"New Brunswick",
			"New Orleans",
			"New York",
			"Northeast Pensylvania",
			"Northern New Jersey",
			"Orange Coast",
			"Orlando",
			"Philadelphia",
			"Pittsburg",
			"Portland",
			"Prince Edward Island",
			"Puebla",
			"Puerto Rico",
			"Puerto Vallarta-Riviera Nayarit",
			"Québec",
			"Queretaro",
			"Raleigh-Durham",
			"Reno-Tahoe",
			"Richmond",
			"Riviera Maya",
			"Sacramento",
			"San Francisco",
			"San Jose",
			"Santa Fe",
			"Saskatoon",
			"Seattle",
			"Southwest Florida",
			"St. John's",
			"Tampa Bay",
			"Taxco",
			"Tijuana-Ensenada",
			"Toronto",
			"Toronto North",
			"Tucson",
			"Vancouver",
			"Veracruz",
			"Victoria",
			"Villa Hermosa",
			"Washington",
			"Winnipeg",
			"==========================",
			"Aachen",
			"Abuja",
			"Accra",
			"Addis Ababa",
			"Adelaide",
			"Ahmedabad",
			"Alanya",
			"Albany",
			"Alice Springs",
			"Alto Adige-Sudtirol",
			"Alto-Valle",
			"Amman",
			"Amsterdam-Haarlem",
			"Andorra",
			"Ankara",
			"Antalya",
			"Argovie",
			"Asuncion",
			"Auckland",
			"Augsburg",
			"Bahrain",
			"Baku",
			"Bali",
			"Bangalore",
			"Bangkok",
			"Bangladesh",
			"Barcelona",
			"Beijing",
			"Belo Horizonte",
			"Bergen",
			"Berlin",
			"Bern",
			"Berner Oberland",
			"Bielefeld",
			"Bodensee",
			"Bodrum",
			"Bogota",
			"Bombay",
			"Bonn",
			"Bourgone",
			"Brasilia",
			"Bremen",
			"Brighton, Sussex & The Channel",
			"Brisbane",
			"Broome",
			"Bruxelles",
			"Bucharest",
			"Budapest",
			"Buenos Aires",
			"Bursa",
			"Cadiz",
			"Cagliari",
			"Cairns",
			"Calcutta",
			"Cambridge and East Anglia",
			"Campina E Regiao",
			"Canberra",
			"Cape Town",
			"Cape Winelands",
			"Capricornia",
			"Caracas",
			"Chemnitz",
			"Chennai",
			"Chiangmai & North Thailand",
			"Christchurch",
			"Cochabamba",
			"Cochin",
			"Colombo",
			"Colonia",
			"Copenhagen",
			"Cordoba",
			"Cork",
			"Corrientes",
			"Côte D'Azur",
			"Cukurova",
			"Cusco",
			"Darmstadt-Sudhessen",
			"Darwin",
			"Del Centro",
			"Delhi",
			"Dublin",
			"Dubrovnik",
			"Durban",
			"Dusseldorf",
			"El Salvador",
			"Engadine",
			"Erfurt-Weimar",
			"Eskisehir",
			"Fethiye",
			"Firenze e Toscana",
			"Fontaleza",
			"Frankfurt Am Main",
			"Freiburg IM Breisbau",
			"Freudenstadt",
			"Fribourg",
			"Friuli Venezia Giulia",
			"Fuji",
			"Galilée",
			"Galway",
			"Garden Route",
			"Garmisch-Partenkirchen",
			"Genève",
			"Girona",
			"Goa",
			"Gold Coast",
			"Gran Canaria",
			"Granada",
			"Graz Steiermark",
			"Grisons",
			"Guam",
			"Guayaquil",
			"Guernsey",
			"Hamburg",
			"Hannover",
			"Harare",
			"Helsinki",
			"Hobart",
			"Hong Kong",
			"Hyderabad",
			"Ibiza",
			"Incheon",
			"Insel Usedom",
			"Isla de Margarita",
			"Istanbul",
			"Izmir",
			"Jakarta",
			"Jerusalem",
			"Jujuy",
			"Kampala",
			"Kaohsiung",
			"Kapadokya",
			"Karachi",
			"Karadeniz",
			"Kathmandu",
			"Kenya Coast",
			"Kerry",
			"Kingston",
			"Koh Samui",
			"Koln",
			"Konya",
			"Krabi",
			"Kuala Lumpur",
			"Kununurra",
			"Kusadasi",
			"Kvarner",
			"Kyrenia",
			"La Paz",
			"La Plata",
			"Lagos",
			"Lanzarote",
			"Launceston",
			"Lausanne",
			"Liège",
			"Lima",
			"Limburg",
			"Linz",
			"Litoral Urugayo",
			"Locarno",
			"Lombardia",
			"London, UK",
			"Lucerne et Suisse centrale",
			"Lugano",
			"Luxembourg",
			"Macau",
			"Mackay",
			"Madrid",
			"Makati",
			"Malaga-Costa Del Sol",
			"Mallorca",
			"Manaus",
			"Manila",
			"Mar del Plata",
			"Marbella",
			"Marmara",
			"Marmaris",
			"Mauritius",
			"Melbourne",
			"Mendoza",
			"Monaco",
			"Montego Bay",
			"Montevideo",
			"Montreux Vevey",
			"Munchen",
			"Nagoya",
			"Nairobi",
			"Nelson Mandela Bay",
			"Northern Ireland",
			"Nouvelle Calédonie",
			"Nurnberg",
			"Osaka",
			"Oslo",
			"Osorno",
			"Palermo",
			"Panama",
			"Paris",
			"Penang",
			"Perth",
			"Phuket",
			"Poona",
			"Port Moresby",
			"Port Vila",
			"Porto",
			"Porto Alegre",
			"Prague",
			"Pretoria",
			"Puerto Madryn",
			"Punta Del Este",
			"Queenstown",
			"Resistencia",
			"Riga",
			"Rio de Janeiro",
			"Roma",
			"Rosario",
			"Rotorua",
			"Salzburg",
			"Salzkammergut",
			"San Isidro",
			"Sanremo E Riviera Dei Fiori",
			"Santa Catarina",
			"Santa Cruz",
			"Santa Fe Parana",
			"Santiago de Chile",
			"Santo Domingo",
			"Sao Paulo",
			"Scotland",
			"Seoul",
			"Sevilla",
			"Singapore",
			"Skål International Headquarters",
			"Sofia",
			"Southampton",
			"Southern Gold Coast",
			"St. Gallen",
			"Stockholm",
			"Stuttgart",
			"Sunshine Coast",
			"Suva",
			"Sydney",
			"Sydney North",
			"Taichung",
			"Taipei",
			"Tallinn",
			"Tegucigalpa",
			"Tel Aviv",
			"Tenerife",
			"Tokyo",
			"Townsville",
			"Tres Frontera",
			"Trivandrum",
			"Troy",
			"Tucuman",
			"Turku",
			"Tyrol",
			"Valparaiso",
			"Var-Provence",
			"Venezia",
			"Viedma Patagones",
			"Villa La Angostura",
			"Wellington",
			"Whitsundays",
			"Wien",
			"Yangon",
			"Zagreb",
			"Zell Am See",
			"Zurich",
		];
	}

	public function RoleInClub()
	{
		return[
			"",
			"Club Board Member",
			"Club Committee Member",
			"Club Member",
			"Young Skål",
			"Club EST",
			"Canada EST",
			"Mexico EST",
			"USA EST",
		]; 
	}

	public function FunctionInClub()
	{
		return[
			"",
			"None",
			"President",
			"Vice-President",
			"Past-president",
			"EST or Treasurer",
			"National Representative",
			"Other"
		];
	}

	public function AttendingCongress()
	{
		return[
			"",
			"Club Voting Delegate # 1",
			"Club Voting Delegate # 2",
			"Club Non Voting Delegate or Member",
			"Club Young Skål",
			"SI Board Member",
			"SI Councillor",
			"Area Committee Member",
			"National Committee Member"
		];
	}

	public function CountryMobileCode()
	{
		print_r(json_decode( file_get_contents(OP_PATH . '/assets/data/country_phone.json' )));
	}

	public static function CountriesState($country)
	{
		//print_r(json_decode(file_get_contents(OP_PATH . '/assets/data/countries.json' ))) ;

		$countries = json_decode(file_get_contents(OP_PATH . '/assets/data/countries.json' )) ;
		foreach ($countries as $country_arr) {
			if ($country_arr->name == $country) {
				return $country_arr->states;
			}
		}
		return false;
	}


}